### ISSUE TITLE
This is only for polish version.

### ISSUE THREAD

**Issue by Doctorrock** [dotnet/AspNetCore.Docs.pl-pl#20]
Please stop wasting your resources to auto translate this pages. "Użyj szablonu projektu kątowego z ASP.NET Core" this translation completely lost meaning. "kątowego" it's literal translation of Angular and nobody in Poland calls Angular "kątowy". This is title and it's already terrible. Your headers are beyond any comprehension. "Uruchom "anie" niezależnie" what is "anie" i don't know that world in polish. "anie" like multiple "Ania"(it's name). Please stop doing that it's making your very good websites being worse than any other tutorial. They are full of grammar mistakes. They don't make sense and also it's offends the authors of this. 

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Użyj szablonu projektu kątowego z ASP.NET Core](https://docs.microsoft.com/pl-pl/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by srvbpigh** [comment]
Hello, @Doctorrock
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Gonzalo-Salines** [comment]
Hello @Doctorrock : 

Thank you for your contribution.
Contributions on translation problems against machine translated content are currently not accepted.
We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.
Microsoft DOCS Global Experience Team

**Comment by Doctorrock** [comment]
Just turn it off. This is unreadable an this page provides negative value for users. Or add button for getting text in English. I'm so tired of this. For such a big company this quality makes you look bad.

**Comment by Doctorrock** [comment]
Oh the button it's there :) Good
