### ISSUE TITLE
Proszę niech tę stronę przeczyta jakiś Polak

### ISSUE THREAD

**Issue by Doctorrock** [dotnet/AspNetCore.Docs.pl-pl#22]
Jeśli jesteś poważna osobą, przeczytaj tę stronę i przekaż komuś że poziom tłumaczenia jest gorzej niż beznadziejny. 

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
* Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
* Content: [Użyj szablonu projektu kątowego z ASP.NET Core](https://docs.microsoft.com/pl-pl/aspnet/core/client-side/spa/angular?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/dotnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/client-side/spa/angular.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-clientside**
* GitHub Login: @SteveSandersonMS
* Microsoft Alias: **stevesa**

**Comment by srvbpigh** [comment]
Hello, @Doctorrock
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Witaj, @Doctorrock !  

Dziękujemy za opinię. Ta strona została przetłumaczona maszynowo, a tekst tłumaczony tą metodą nie zawsze jest całkowicie zrozumiały. Niedawno po prawej stronie dodaliśmy opcję „Czytaj w języku angielskim”, która umożliwia zmianę wersji językowej na angielską bez konieczności zmiany ustawień języka.  

Pozdrawiamy,  

Międzynarodowy zespół witryny Microsoft DOCS
