### ISSUE TITLE
Visual Studio Code Instructions unclear

### ISSUE THREAD

**Issue by Kaszanas** [dotnet/AspNetCore.Docs.pl-pl#25]
When attempting to install and test Blazor WebAssembly environment point number 2 is not clear and states:

> Opcjonalnie można zainstalować szablon Blazor webassembly Preview, uruchamiając następujące polecenie:

When omitting this step and going straight onto further steps there is an issue that is apparent on step 5 and results in following error:
```
dotnet new blazorwasm -o TestingBlazorWASM
Couldn't find an installed template that matches the input, searching online for one that does...
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --dry-run           Displays a summary of what would happen if the given command line were run if it would result in a template creation.
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.
  --update-check      Check the currently installed template packs for updates.
  --update-apply      Check the currently installed template packs for update, and install the updates.


No templates matched the input template name: blazorwasm.
```

In turn that means that step 2 is not optional as the issue is solved after performing the required action that is specified by step 2.

This might be due to translation issues from English -> Polish as there is no clear context as to which the instructions "optionally" apply to.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Wprowadzenie do ASP.NET CoreBlazor](https://docs.microsoft.com/pl-pl/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @Kaszanas ... "Optionally" in this context (in English) means "if you plan to create Blazor WebAssembly apps." Yes, you're right ... it's not optional if you want to make Blazor WebAssembly apps.

I don't think that there's a need to change it right now. Version 3.2 will be out in a little while. As soon as it comes out, the separate template install step won't be required because Blazor WebAssembly will be released and included in the SDK.

**Comment by srvbpigh** [comment]
Hello, @Kaszanas
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by Kaszanas** [comment]
@guardrex - agreed but when 2 contexts are existing it's hard to know which one the optional step applies to.

I would go with something more specific, like:

2. OPTIONALLY: If You want to use Blazor WebAssembly functionality there is a template project available for You by applying following command:
`command text'
Please note that further steps are dependent on the specified command.

Thank You for the information @srvbpigh 

I got it working in the end.

**Comment by guardrex** [comment]
Yes, but that text is going to **_drop soon_**. There's no point under the heavy workload to change it right this second. I also have in-progress work that might conflict with such an update. Hold on for a little while until 3.2 ships and this line will go ...

&mdash; *To the land of wind and ghosts.* - &copy;2019 Ryan Nowak

:smile:

**Comment by Kaszanas** [comment]
Sure thing! @guardrex 

As I said I got it working in the end so it is all fine ;)
