### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by Kaszanas** [dotnet/AspNetCore.Docs.pl-pl#26]
Website states:
> Na pasku bocznym są dostępne wiele stron:
> - Domowy
> - Licznik
> - Pobieranie danych

Alternative:
Na pasku bocznym dostępnych jest wiele stron:
- Strona Główna??
- Licznik
- Pobieranie danych

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: c07e57dc-526f-9479-4695-de7d8f06eb9a
* Version Independent ID: 8226ed72-69b2-3c93-a931-218bd11cf9c8
* Content: [Wprowadzenie do ASP.NET CoreBlazor](https://docs.microsoft.com/pl-pl/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code)
* Content Source: [aspnetcore/blazor/get-started.md](https://github.com/dotnet/AspNetCore.Docs.pl-pl/blob/live/aspnetcore/blazor/get-started.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @Kaszanas
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Hello @Kaszanas :

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

cc @JasonCard
